### ISSUE TITLE
Support for earlier versions of Rails? 

### ISSUE THREAD

**Issue by etagwerker** [manuelmeurer/railsbump#58]
Hey @manuelmeurer, 

Congratulations on releasing 1.0! It looks great! 

I was wondering if you had any plans to support older versions of Rails? At work we have been getting a steady stream of Rails 2.3 client projects, so we would be interested in seeing compatibility data for Rails 3.0, 3.1, 3.2, 4.0, and 4.1. 

I realize that it has been many years since those versions were deprecated but there are a lot of companies out there using these versions still. 😄 

I realize also that I could probably use `next_rails` to check compatibility for those old projects. So that is a good workaround. 

Anyway, I thought I should bring it up in case you had any ideas on this. 

Thanks!

**Comment by manuelmeurer** [comment]
Thanks, @etagwerker!

I thought about which versions to include early on and decided on >= 4 and the latest minor versions. So once Rails 6.1 is out, it will be displayed instead of Rails 6.0 and all the compatibility checks will be run again automatically.

I'm hesitant to add Rails 2.x and 3.x since on the one hand, I don't know how many apps with those versions are still in use (I think you are an outlier since your business is to maintain/upgrade old Rails apps 😄), and on the other hand, my little Sidekiq instance is already creaking with the workload that 3 Rails versions are generating. :) Adding another version will generate a third more work, i.e. it will take that much longer to check each new gem/lockfile...

**Comment by etagwerker** [comment]
@manuelmeurer Thanks for the quick response! As you said, my company has a special interest in checking older versions of Rails. At the moment we are working on three different Rails 2.3 upgrade projects. 😄 

I'm wondering if it might be worth it for me and my company to deploy a clone of RailsBump.org that supports older versions (2.3 to 4.2) -- As RailsBump stops supporting old versions, we can start supporting them in my application instance.

How does that sound?

**Comment by etagwerker** [comment]
@manuelmeurer I like the idea of sponsoring the project in order to have an instance that is accessible to everyone. 😄 

> Or were you talking about a private instance, only accessible to your and your company?

We would want it to be public for everyone. 

Maybe we can do a quick call next week to talk about this?

**Comment by manuelmeurer** [comment]
@etagwerker All minor Rails versions from 2.3 up to 6.0 are added now and visible in the table. 🙌

**Comment by etagwerker** [comment]
@manuelmeurer Awesome, thank you! I talked a little bit about your project in episode 100 of the Remote Ruby podcast. ❤️ 

https://remoteruby.transistor.fm/100

**Comment by manuelmeurer** [comment]
Yeah, I saw some traffic coming from there in the new analytics dashboard: https://plausible.io/railsbump.org
Already added the episode to my Podcast app! 😄 👍
